name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
        compiler: [gcc, clang]
    env:
      CMAKE_BUILD_TYPE: ${{ matrix.build_type }}
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y cmake g++ clang
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTS=ON
        env:
          CC: ${{ matrix.compiler == 'clang' && 'clang' || 'gcc' }}
          CXX: ${{ matrix.compiler == 'clang' && 'clang++' || 'g++' }}
      - name: Build
        run: cmake --build build -j
      - name: Test
        run: ctest --test-dir build --output-on-failure

  bench-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y cmake g++
      - name: Configure (profiled)
        run: cmake -S . -B build-prof -DCMAKE_BUILD_TYPE=Release -DSSSP_PROFILE=ON -DBUILD_BENCHMARKS=ON -DBUILD_TESTS=ON
      - name: Build (profiled)
        run: cmake --build build-prof -j
      - name: Test (profiled)
        run: ctest --test-dir build-prof --output-on-failure
